### ISSUE TITLE
How to enable ASM on cross compile binaries

### ISSUE THREAD

**Issue by mxaddict** [herumi/mcl#102]
We are building with MCL using a cross compile build  on a x86_64 linux host

We get some compile errors when enabling ASM support on anything other than the native system build

Do you happen to know what we would need to change to support ASM on osx, arm, aarch, windows (mingw) builds from a linux host build?

**Comment by herumi** [comment]
I can get the arm64 binary of `bin/bn_test.exe` as the following steps:

Install
- `gcc-10-aarch64-linux-gnu`
- `g++-10-aarch64-linux-gnu`
- `llvm-11`.

```
make src/gen # src/gen is for host program
make bin/bn_test.exe PRE=aarch64-linux-gnu- CC=gcc-10 CXX=g++-10 ARCH=aarch64 UPDATE_ASM=1 LLVM_VER=-11 MCL_USE_GMP=0
```

**Comment by aguycalled** [comment]
is xbyak faster than asm for every os or only windows? what is the faster for each os?

**Comment by herumi** [comment]
The xbyak version is faster on all x86-64 OS.
mcl uses
- xbyak version if mulx, adox and adcx (Broadwell or later) are available and JIT code is available,
- otherwise the asm version generate by LLVM.

If you can use clang for cross-compile, then to compile src/base64.ll directly without generating *.s.
cf. https://github.com/herumi/bls-eth-go-binary/blob/master/Makefile
