### ISSUE TITLE
Removing any ETH related functions from the library

### ISSUE THREAD

**Issue by b00f** [herumi/mcl#139]
ETH functions made this library a bit messy. In my point of view MCL and BLS libraries should follow the original spec and not ETH spec. If Ethereum community needs something special on top of that, they cam fork this library.

**Comment by herumi** [comment]
Yes, there is messy code in my library, and I would like to refactor something.

However, since this library was widely used before the Ethereum consensus layer (ETH2) and IRTF specifications were finalized, I don't want to make any changes that would break backward compatibility as much as possible.

**Comment by b00f** [comment]
@herumi I think we can close this issue now and later work on it. Thanks for the explanation
