### ISSUE TITLE
What is that mean "make bin/filename.exe && bin/filename.exe" ?

### ISSUE THREAD

**Issue by NP-h** [herumi/mcl#166]
Hi herumi,
It is not a critical question, but really i want to know what is that mean..
In my opinion, when i use Cpp(C++) or C with gcc then normally combine command like "gcc filename.c" or combine object "gcc -o filename.c filename2.c "

what is the different point ?? 
when i use this library "gcc mysource.cpp" is not compiled with error(can't fine header)
but when i use "make bin/filename.exe && bin/filename.exe" is working well.

can you teach me? please let me know if you can.

Thank you

**Comment by herumi** [comment]
You should use `g++ mysource.cpp` instead of `gcc mysource.cpp`, and specify `-I <include dir>` and linker options.
Simply, move mysource.cpp to mcl/sample, and type `make bin/mysource.exe && bin/mysource.exe`.

But you seem not to be good at C++. What language do you specialize in?
If you can use JavaScript, then please try https://github.com/herumi/mcl-wasm .

**Comment by NP-h** [comment]
Thank you always!
