### ISSUE TITLE
struct ecdsaPrecomputedPublicKey not defined.

### ISSUE THREAD

**Issue by fionser** [herumi/mcl#25]
I am trying to call `mcl/ecdsa.h` from go, but I found that the struct `ecdsaPrecomputedPublicKey`  is not defined anywhere.

**Comment by herumi** [comment]
The contents of `ecdsaPrecomputedPublicKey` is private, so keep the pointer generated by `ecdsaPrecomputedPublicKeyCreate` in cgo and delete it by `ecdsaPrecomputedPublicKeyDestroy` after it is not used.
But it is better to use other implementation of ecdsa because I made it for test and it is not optimized.
